


import { animate, animation, keyframes, style, trigger, transition, useAnimation } from '@angular/animations';


export const wobbleAnimation = animation([
    animate(
        '0.5s',
        keyframes([
            style({ transform: 'translateX(0%)', offset: 0 }),
            style({ transform: 'translateX(-25%) rotate(-5deg)', offset: 0.15 }),
            style({ transform: 'translateX(20%) rotate(3deg)', offset: 0.3 }),
            style({ transform: 'translateX(-15%) rotate(-3deg)', offset: 0.45 }),
            style({ transform: 'translateX(10%) rotate(2deg)', offset: 0.6 }),
            style({ transform: 'translateX(-5%) rotate(-1deg)', offset: 0.75 }),
            style({ transform: 'translateX(0%)', offset: 1 }),
        ])
    )
]);

export const wobbleTrigger = trigger('wobble', [
    transition('false => true', [
        useAnimation(wobbleAnimation)
    ])
]);

// Generated by Copilot